"""Base strategy class for all trading strategies"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Signal:
    """Trading signal generated by a strategy"""

    market_id: str
    side: str  # 'buy' or 'sell'
    confidence: float  # 0.0 to 1.0
    size: float
    price: Optional[float] = None
    timestamp: datetime = None
    metadata: Dict[str, Any] = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.metadata is None:
            self.metadata = {}


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies
    """

    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.is_active = False
        self.positions: Dict[str, float] = {}

    @abstractmethod
    def analyze(self, market_data: Dict[str, Any]) -> Optional[Signal]:
        """
        Analyze market data and generate trading signals

        Args:
            market_data: Market data including price, volume, order book, etc.

        Returns:
            Signal object if opportunity found, None otherwise
        """
        pass

    @abstractmethod
    def should_enter(self, market_data: Dict[str, Any]) -> bool:
        """
        Determine if strategy should enter a position

        Args:
            market_data: Current market data

        Returns:
            True if should enter position
        """
        pass

    @abstractmethod
    def should_exit(self, market_data: Dict[str, Any]) -> bool:
        """
        Determine if strategy should exit a position

        Args:
            market_data: Current market data

        Returns:
            True if should exit position
        """
        pass

    def validate_signal(self, signal: Signal) -> bool:
        """
        Validate a trading signal before execution

        Args:
            signal: Signal to validate

        Returns:
            True if signal is valid
        """
        # Basic validation
        if signal.confidence < 0 or signal.confidence > 1:
            return False
        if signal.side not in ["buy", "sell"]:
            return False
        if signal.size <= 0:
            return False

        return True

    def update_position(self, market_id: str, size: float):
        """
        Update position tracking

        Args:
            market_id: Market identifier
            size: Position size (positive for long, negative for short)
        """
        self.positions[market_id] = self.positions.get(market_id, 0) + size

    def get_position(self, market_id: str) -> float:
        """
        Get current position in a market

        Args:
            market_id: Market identifier

        Returns:
            Current position size
        """
        return self.positions.get(market_id, 0)

    def start(self):
        """Start the strategy"""
        self.is_active = True

    def stop(self):
        """Stop the strategy"""
        self.is_active = False

    def reset(self):
        """Reset strategy state"""
        self.positions = {}
        self.is_active = False
